name: Test and lint code
run-name: Test and lint code

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

defaults:
 run:
  working-directory: frontend

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'frontend'
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json

      - run: ls
          
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  e2e-test:
    name: Run E2E tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'frontend'
    
      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests
        run: npx playwright test
        
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'frontend'

      - run: cd frontend

      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint